name: Issue Created

on:
  issues:
    types: [opened]

jobs:
  run-python-script:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.10'

    - name: Install dependencies
      run: pip install gidgethub

    - name: Run Python script
      run: python .github/workflows/scripts/add_community_issue_labels.py
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        ISSUE_AUTHOR: ${{ github.actor }}
        ISSUE_NUMBER: ${{ github.event.issue.number }}
        REPO: ${{ github.action_repository }}
