name: Label community issues

on:
  issues:
    types:
      - opened

jobs:
  label_community_issues:
    runs-on: ubuntu-latest
    permissions:
      issues: write
    if: |
      collaborators=$(gh api /repos/elastic/connectors/collaborators --jq '.[] | .login')
      teams=$(gh api /repos/elastic/connectors/teams --jq '.[] | .id')
      echo "::notice::****"
      echo collaborators
      echo "::notice::****"
      echo teams
      echo "::notice::****"
    steps:
      - run: gh issue edit "$NUMBER" --add-label "$LABELS"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
          NUMBER: ${{ github.event.issue.number }}
          LABELS: community-driven,needs-triage
